events {}
http {
    # 1. Cấu hình Upstream Load Balancer 
    upstream web_servers {
        server 10.10.10.10:80;
        server 10.10.10.11:80;
    }

    server {
        listen 80;

        # 2. Web tĩnh (Trỏ vào Upstream Load Balancer thay vì 1 server)
        location / {
            proxy_pass http://web_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 3. App API (strip /api/)
        location /api/ {
            proxy_pass http://application-backend-server:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 4. Keycloak
        location /auth/ {
            # Bỏ dấu / ở cuối 8080 để Nginx truyền nguyên vẹn /auth/ xuống backend
            proxy_pass          http://authentication-identity-server:8080; 
            
            # Dùng $http_host để truyền localhost:5173 thay vì localhost
            proxy_set_header    Host               $http_host;
            proxy_set_header    X-Real-IP          $remote_addr;
            proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto  $scheme;
            
            # Các header này hỗ trợ Keycloak nhận diện đúng môi trường proxy
            proxy_set_header    X-Forwarded-Host   $http_host;
            proxy_set_header    X-Forwarded-Port   $server_port;

            proxy_connect_timeout 90s;
            proxy_send_timeout    90s;
            proxy_read_timeout    90s;
        }

        # 5. API Mở rộng: Đọc danh sách sinh viên JSON (Phần mở rộng 9)
        location /student/ {
            proxy_pass http://application-backend-server:8081/student;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}